 
; -------------------------------------------------------------------
;
; Database Management
;
; -------------------------------------------------------------------

(defun database-setup ()
  (defun assign-properties  (carrier-list coordinates)
    (cond((and(null carrier-list) (null coordinates))nil)
	 ((null carrier-list)
	  (setf (get (intern (caar coordinates)) 'x-coord) (cadar coordinates))
	  (setf (get (intern (caar coordinates)) 'y-coord) (caddar coordinates))
	  (assign-properties carrier-list (cdr coordinates)))
           
              ;(setf (get (intern(caar dis-list)) 'distance) 
               ;     (cons (cdar dis-list)
               ;           (get (intern(caar dis-list)) 'distance)))
             ; (setf (get (intern(cadar dis-list)) 'distance) 
              ;      (cons (cons (caar dis-list) (cddar dis-list))
               ;           (get (intern(cadar dis-list)) 'distance)))
          (t (setf (get(intern(cadar carrier-list))(caar carrier-list))
                    (cons (caddar carrier-list)
                          (get (intern(cadar carrier-list))
                               (caar carrier-list))))
              (assign-properties (cdr carrier-list)coordinates))))
           
   ; city x y         
  (let((coordinates
	'(("seattle" 0 1500) ; 
	  ("sanfrancisco" 150 1020)
	  ("losangeles" 300 300)
	  ("boise" 360 1260)
	  ("phoenix" 510 210)
	  ("durango" 840 660)
	  ("albuquerque" 900 300)
	  ("denver" 900 1020)
	  ("bismark" 1440 1470)
	  ("dallas" 1500 150)
	  ("witchita" 1500 750)
	  ("oklahomacity" 1770 300)
	  ("minneapolis" 1890 1280)
	  ("neworleans" 2100 120)
	  ("memphis" 1800 450)
	  ("stlouis" 2100 750)
	  ("springfield" 2250  1050)
	  ("roanoke" 2340 1020)
	  ("westpalm" 2370 60)
	  ("miami" 2400 0)
	  ("pittsburgh" 2400 1200)
	  ("ithaca" 2610 1260)
	  ("baltimore" 2640 990)
	  ("newark" 2670 1020)
	  ("philadelphia" 2700 1050)
	  ("boston" 2850 1290)
	  ("bangor" 3000 1440)))
       
        (carriers
          '(
            (fly "bangor" "ithaca")
	    (take-bus "boise" "seattle")
	    (take-bus "seattle" "boise")
	    (take-train "denver" "phoenix")
	    (take-bus "denver" "phoenix")
	    (take-train "sanfrancisco" "losangeles")
	    (take-train "seattle" "losangeles")
	    (fly "memphis" "seattle")
	    (take-train "boise" "witchita")
	    (take-bus "witchita" "boise")
	    (take-train "miami" "seattle")
	    (fly "dallas" "minneapolis")
            (take-train "dallas" "losangeles")
	    (fly "miami" "dallas")
	    (take-train "dallas" "witchita")
	    (take-bus "dallas" "witchita")
	    (take-bus "duarango" "denver")
	    (take-bus "denver" "durango")
            (take-bus "philadelphia" "ithaca")
            (take-bus "miami" "westpalm")
            (fly "boston" "losangeles")
            (fly "roanoke" "memphis")
            (take-train "memphis" "stlouis")
            (take-bus "roanoke" "miami")
            (fly "miami" "philadelphia")
            (take-train "miami" "stlouis")
            (fly "miami" "ithaca")
            (fly "denver" "miami")
	    (fly "boston" "newark")
            (fly "boston" "bangor")
	    (fly "bangor" "boston")
            (fly "westpalm" "baltimore")
            (fly "baltimore" "philadelphia")
            (fly "philadelphia" "newark")
            (fly "newark" "boston")
            (fly "westpalm" "pittsburgh")
            (fly "pittsburgh" "philadelphia")
            (fly "denver" "stlouis")
            (fly "denver" "baltimore")
            (fly "stlouis" "boston")
            (fly "miami" "boston")
            (take-train "boston" "westpalm")
            (fly "miami" "stlouis")
            (fly "stlouis" "philadelphia")
            (fly "philadelphia" "stlouis")
            (take-bus "denver" "miami")
            (take-bus "denver" "boston")
            (take-bus "philadelphia" "baltimore")
            (fly "philadelphia" "baltimore")
            (fly "baltimore" "miami")
            (take-bus "philadelphia" "newark"))))
     (assign-properties  carriers coordinates)))

